/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ECDHKeys {
  public: Uint8Array
  shared: Uint8Array
}
export function xed25519_ecdh(peerPublicKey: Uint8Array, clientPrivateKey?: Uint8Array | undefined | null): ECDHKeys
